Ruby on Rails/tasty_treats/config/routes.rb
Rails.application.routes.draw do
  root "recipes#index"
  resources :recipes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  
end

Ruby on Rails/tasty_treats/app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

Ruby on Rails/tasty_treats/app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :ingredients, dependent: :destroy
    accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :all_blank
end

Ruby on Rails/tasty_treats/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: %i[ show edit update destroy ]

  # GET /ingredients or /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1 or /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients or /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully created." }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1 or /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully updated." }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1 or /ingredients/1.json
  def destroy
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: "Ingredient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ingredient_params
      params.fetch(:ingredient, {})
    end
end

Ruby on Rails/tasty_treats/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @recipe.ingredients.build
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.fetch(:recipe, {}).permit(:title, :instructions, ingredients_attributes: [:id, :name, :quantity, :_destroy])
    end
end

Ruby on Rails/tasty_treats/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

Ruby on Rails/tasty_treats/app/helpers/recipes_helper.rb
module RecipesHelper
end

Ruby on Rails/tasty_treats/app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient) do |form| %>
  <% if ingredient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% ingredient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Ruby on Rails/tasty_treats/app/views/ingredients/_ingredient.html.erb
<div id="<%= dom_id ingredient %>">
</div>

Ruby on Rails/tasty_treats/app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render "form", ingredient: @ingredient %>

<br>

<div>
  <%= link_to "Show this ingredient", @ingredient %> |
  <%= link_to "Back to ingredients", ingredients_path %>
</div>

Ruby on Rails/tasty_treats/app/views/ingredients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ingredients</h1>

<div id="ingredients">
  <% @ingredients.each do |ingredient| %>
    <%= render ingredient %>
    <p>
      <%= link_to "Show this ingredient", ingredient %>
    </p>
  <% end %>
</div>

<%= link_to "New ingredient", new_ingredient_path %>

Ruby on Rails/tasty_treats/app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render "form", ingredient: @ingredient %>

<br>

<div>
  <%= link_to "Back to ingredients", ingredients_path %>
</div>

Ruby on Rails/tasty_treats/app/views/ingredients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ingredient %>

<div>
  <%= link_to "Edit this ingredient", edit_ingredient_path(@ingredient) %> |
  <%= link_to "Back to ingredients", ingredients_path %>

  <%= button_to "Destroy this ingredient", @ingredient, method: :delete %>
</div>

Ruby on Rails/tasty_treats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TastyTreats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Ruby on Rails/tasty_treats/app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :title%>
  <%= form.text_field :title %>
  <%= form.label :instructions %>
  <%= form.text_field :instructions %>

  <div id="ingredients">
    <%= form.fields_for :ingredients do |ingredient_fields| %>
      <div class="ingredient">
        <div class="field">
          <%= ingredient_fields.label :name %>
          <%= ingredient_fields.text_field :name %>
        </div>

        <div class="field">
          <%= ingredient_fields.label :quantity %>
          <%= ingredient_fields.number_field :quantity %>
        </div>
        <%= link_to "Remove", "#", class: "remove_fields" %>
      </div>
    <% end %>
  </div>

<p><%= link_to "Add Ingredient", "#", class: "add_fields", data: { target: "#ingredients" } %></p>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<script>
  document.addEventListener("click", function(event) {
    var target = event.target;
    if (target.classList.contains("add_fields")) {
      event.preventDefault();

      var targetSelector = target.getAttribute("data-target");
      var targetNode = document.querySelector(targetSelector);
      var firstField = targetNode.querySelector(".ingredient:first-of-type");
      var newField = firstField.cloneNode(true);
      var inputFields = newField.querySelectorAll("input");
      inputFields.forEach(function(field) {
        field.value = "";
        field.name = field.name.replace(/\d+/, function(match) {
          return parseInt(match) + 1;
        });
      });
      targetNode.appendChild(newField);
    } else if (target.classList.contains("remove_fields")) {
      event.preventDefault();

      var field = target.closest(".ingredient");
      field.parentNode.removeChild(field);
    }
  });
</script>

Ruby on Rails/tasty_treats/app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
</div>

Ruby on Rails/tasty_treats/app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

Ruby on Rails/tasty_treats/app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipes</h1>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
    <p>
      <%= link_to "Show this recipe", recipe %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe", new_recipe_path %>

Ruby on Rails/tasty_treats/app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

Ruby on Rails/tasty_treats/app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @recipe.title %></h1>
<p><%= @recipe.instructions %></p>

<h2>Ingredients</h2>
<ul>
  <% @recipe.ingredients.each do |ingredient| %>
    <li><%= ingredient.name %> (<%= ingredient.quantity %>)</li>
  <% end %>
</ul>

<div>
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
  <%= link_to "Back to recipes", recipes_path %>

  <%= button_to "Destroy this recipe", @recipe, method: :delete %>
</div>