Ruby on Rails/planter/config/routes.rb
Rails.application.routes.draw do
  resources :plants
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "plants#index"
end

Ruby on Rails/planter/app/models/person.rb
class Person < ApplicationRecord
    validates :email, :name, presence: true

    has_many :plants
end

Ruby on Rails/planter/app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :person
end

Ruby on Rails/planter/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:email, :name)
    end
end

Ruby on Rails/planter/app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: %i[ show edit update destroy ]

  # GET /plants or /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1 or /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants or /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to plant_url(@plant), notice: "Plant was successfully created." }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1 or /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to plant_url(@plant), notice: "Plant was successfully updated." }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1 or /plants/1.json
  def destroy
    @plant.destroy

    respond_to do |format|
      format.html { redirect_to plants_url, notice: "Plant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plant_params
      params.require(:plant).permit(:name, :person_id)
    end
end

Ruby on Rails/planter/app/helpers/people_helper.rb
module PeopleHelper
end

Ruby on Rails/planter/app/helpers/plants_helper.rb
module PlantsHelper
end

Ruby on Rails/planter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "pico", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body class="container">
  <header>
  <h1>Planter</h1>
  <nav>
  <ul>
  <li><%= link_to "People", people_path %></li>
  <li><%= link_to "Plants", plants_path %></li>
  </ul>
  </nav>
  </header>
  <main>
  <%= yield %>
  </main>

  </body>
</html>

Ruby on Rails/planter/app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Ruby on Rails/planter/app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <strong>Email:</strong>
    <%= person.email %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= person.name %>
  </p>

  <p>
  <strong>Plants:</strong>
  <ul>
  <% person.plants.each do |plant| %>
  <li><%= link_to plant.name, plant_path(plant) %></li>
  <% end %>
  </ul>
  </p>

</div>

Ruby on Rails/planter/app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", @person %> |
  <%= link_to "Back to people", people_path %>
</div>

Ruby on Rails/planter/app/views/people/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>People</h1>

<div id="people">
  <% @people.each do |person| %>
    <%= render person %>
    <p>
      <%= link_to "Show this person", person %>
    </p>
  <% end %>
</div>

<%= link_to "New person", new_person_path %>

Ruby on Rails/planter/app/views/people/new.html.erb
<h1>New person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Back to people", people_path %>
</div>

Ruby on Rails/planter/app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div>
  <%= link_to "Add new plant", new_plant_path(person_id: @person.id) %>
  <%= link_to "Edit this person", edit_person_path(@person) %> |
  <%= link_to "Back to people", people_path %>

  <%= button_to "Destroy this person", @person, method: :delete %>
</div>

Ruby on Rails/planter/app/views/plants/_form.html.erb
<%= form_with(model: plant) do |form| %>
  <% if plant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
        <% plant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :person_id, style: "display: block" %>
    <%= form.select:person_id, Person.all.collect { |p| 
    [p.name, p.id]}, 
    include_blank: "Pick a person", selected: params[:person_id] %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Ruby on Rails/planter/app/views/plants/_plant.html.erb
<div id="<%= dom_id plant %>">
  <p>
    <strong>Name:</strong>
    <%= plant.name %>
  </p>

  <p>
    <strong>Person:</strong>
    <%= link_to plant.person.name, person_path(plant.person) %>
  </p>

</div>

Ruby on Rails/planter/app/views/plants/edit.html.erb
<h1>Editing plant</h1>

<%= render "form", plant: @plant %>

<br>

<div>
  <%= link_to "Show this plant", @plant %> |
  <%= link_to "Back to plants", plants_path %>
</div>

Ruby on Rails/planter/app/views/plants/index.html.erb
<p style="color: green"><%= notice %></p>


<h1>Plants</h1>


<div id="plants">
  <% @plants.each do |plant| %>
    <%= render plant %>
    <p>
      <%= link_to "Show this plant", plant %>
    </p>
  <% end %>
</div>

<%= link_to "New plant", new_plant_path %>

Ruby on Rails/planter/app/views/plants/new.html.erb
<h1>New plant</h1>

<%= render "form", plant: @plant %>

<br>

<div>
  <%= link_to "Back to plants", plants_path %>
</div>

Ruby on Rails/planter/app/views/plants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @plant %>

<div>
  <%= link_to "Edit this plant", edit_plant_path(@plant) %> |
  <%= link_to "Back to plants", plants_path %>

  <%= button_to "Destroy this plant", @plant, method: :delete %>
</div>